### PR TITLE
fix tox links

### PR DESCRIPTION
**Pull request by grexi**
The current tox links lead to a 404.

### CODE REVIEW

**Review by jsirois — APPROVED** [review]
Thanks @grexi.

**Comment by jsirois** [comment]
@grexi you'll need to merge upstream main to pick up the fix for the `format-check,typecheck,vendor-check,package` shard.

**Comment by grexi** [comment]
@jsirois : Done. Thanks for the help :+1:

**Comment by jsirois** [comment]
Man, you just get all the bad luck @grexi. The wheel project has happened to start [releasing again](https://pypi.org/project/wheel/#history) after a ~year hiatus and that exposed a bug in Pex vendoring machinery. I have a real fix out here: https://github.com/pantsbuild/pex/pull/1979

As soon as that is in main I'll ping you again to rebase. That should be the last time needed!

**Comment by jsirois** [comment]
Ok. @grexi you can now re-merge upstream main again. This time CI should go green.

**Comment by grexi** [comment]
:crossed_fingers:

**Comment by jsirois** [comment]
Thanks for your patience on that @grexi and thank you for the fix.

**Pull request merged**
