### PR TITLE
Pass allow_prerelease to other iterators (Static, Caching)

### PR DESCRIPTION
**Pull request by toddgardner**
Not sure if this is the best way to do this or test this, but while investigating another bug I noticed caching resolver always ignored prerelease versions, as it constructed it's own iterator and didn't take into account the options passed on resolve. This fixes that and tests it.

### CODE REVIEW

**Comment by toddgardner** [comment]
I found another issue of the same nature, where allow_prerelease wasn't being passed to StaticIterator either, this meant two requirements like `pantsbuild.pants>=1.3.0.dev1` and `pantsbuild.pants==1.3.0.dev14` could never be satisfied, since the static iterator would exclude all prereleases regardless of allow_prereleases.

I rolled it into this change since it touched the same code.

Note this will have to be updated if #374 is accepted as it includes defaults that should be updated.

**Comment by bloomonkey** [comment]
+1
I think I'm getting bitten by this too - a dependency of one of my dependencies is a pre-release.

**Comment by jsirois** [comment]
@toddgardner - #374 is now merged, please update.

**Comment by toddgardner** [comment]
Updated and added some tests for the defaults.

**Pull request merged**
