### PR TITLE
Use Travis's container-based infrastructure

### PR DESCRIPTION
**Pull request by rouge8**
Jobs on the container-based infrastructure should start faster.

### CODE REVIEW

**Comment by rouge8** [comment]
Replaced by #168

**Comment by jsirois** [comment]
Aha - did not see this.  I just started helping out on pex maintenance.

Thanks for having done this despite being trampled.

**Comment by piotr-dobrogost** [comment]
Actually for pip they are slower – https://github.com/pypa/pip/pull/3095

**Comment by jsirois** [comment]
We shall see as CI runs accumulate, there is more at play than pip here.  Pex has many shards to schedule, and that may give an overall win.  We've had 1 container based build land and the variances are high, but it is ~10% faster overall: https://travis-ci.org/pantsbuild/pex/builds.

For pants - which also has many shards - the win was noticeable.  We switched back on 2014-12-19 and have been happy customers.

**Pull request closed without merging**
