### PR TITLE
Extract global configuration.

### PR DESCRIPTION
**Pull request by jsirois**
This lifts Pex global configuration in pex.commands for re-use in the
`pex3` CLI.

Work towards #1401.
Depends on #1462.

### CODE REVIEW

**Comment by jsirois** [comment]
Please just review the second commit (b8eb20f), the first commit (78d29f0) is out for review in #1462.

**Comment by jsirois** [comment]
This is the last pre-work for landing the platform specific `pex3 lock create ...` command.

**Comment by chrisjrn** [comment]
👀

**Review by chrisjrn — APPROVED** [review]
This looks OK

**Comment by jsirois** [comment]
Thanks @chrisjrn. @Eric-Arellano I'll still need a look by you or someone else to merge. Let me know if I should pull someone else in.

**Review by Eric-Arellano — APPROVED** [review]

**Pull request merged**
