### PR TITLE
VCS Resolvable

### PR DESCRIPTION
**Pull request by adeandrade**
We rely on the `pip` package to export the repo into a temporary location and let `ResolvableDirectory` do the rest of the work.

### CODE REVIEW

**Comment by adeandrade** [comment]
As described in: https://github.com/pantsbuild/pex/issues/93

**Comment by adeandrade** [comment]
There's a problem with `setuptools` in the way it is reading a package definition. It does not return the URL with the package.

**Comment by bendidi** [comment]
hello, thanks for your work, any news on when this would land?
would be glad to help if you give me direction to complete your work :)

**Comment by jsirois** [comment]
@adeandrade vendoring pip is pretty heavyweight just to get vcs resolvables. It's not out of the question as a move for pex to make, but if we make it it would seem to make sense to let pip take over resolution completely - folks expect pex resolves to work just like pip resolves and sometimes they do not. This would fix manylinux2010+ support and other similar issues. See:
+ #771
+ #763
+ #768
+ #761

Pip is a large package though, adding ~5MB IIRC to pex which currently sits at 3MB + due to vendoring setuptools.

**Comment by jsirois** [comment]
Thanks for helping spur movement here @adeandrade. Now that Pex 2+ uses pip internally, VCS requirements are fully supported. I'm going to close this PR as a result.

**Pull request closed without merging**
