### PR TITLE
Reject VCS requirements in locks.

### LINKED ISSUE #1562: Support VCS requirements 1st class
Right now Pex requirement parsing lumps these under `URLRequirement` precluding any special handling required. One way or another #1556 will require recognizing VCS requirements.

### PR DESCRIPTION
**Pull request by jsirois**
The current pex lock infrastructure cannot handle VCS requirements in
the same way it can't handle local project requirements. Unlike local
project requirements though, the failure to handle these requirements
was uncontrolled. Add explicit parsing of VCS requirements to allow them
to be singled out and rejected along side local project requirements.

This addresses the UX for the failure noted in #1556 but may not be the
final word there. If there is a desire to actually handle VCS
requirements in locks, the `VCSRequirement` parsing added here can be
expanded to extract the needed extra data (commit id certainly) to build
that support.

Closes #1562

### CODE REVIEW

**Comment by jsirois** [comment]
This is good to go for review despite red. The failure is independent bitrot being addressed in #1564. I'll re-base this (and #1561) once this lands.

**Review by stuhood — COMMENTED** [review]
Content looks good, and the parsing is a great step toward https://github.com/pantsbuild/pex/issues/1562. But I do wonder if this shouldn't be a strongly worded warning rather than an error, or perhaps whether failing should be behind an option (on by default is fine).

Although these requirements will be uncontrolled, as we migrate users in Pants to lockfiles by default, erroring for this case will inhibit some users from using lockfiles who might otherwise have been able to lock the rest of their requirements. So it might be good for Pants to be able to detect the requirement, warn the user with a ticket number, but then pass an option to PEX to skip erroring so that the rest of their requirements can be locked at least.

Thoughts?

**Comment by jsirois** [comment]
> But I do wonder if this shouldn't be a strongly worded warning rather than an error

We can do nothing except error right now. There will be extensive work needed to support not erroring. You may not be aware, but Pants currently does not error ... but does the wrong thing and silently locks the latest publically available version of the project from PyPI instead of grabbing the requested VCS version and locking that.

**Comment by jsirois** [comment]
> ... and the parsing is a great step toward #1562

The parsing is exactly #1562. It resolves that. The notes at the bottom of that issue are contingent on the answer to #1556 which I expect is do all the hard work. But we could also just proceed as is with failing and circle back later and advance the state of the art. The current failure is slightly better than the Pants state with the silent ignore what you said behavior.

**Comment by jsirois** [comment]
@stuhood if it helps focus: This just takes the current backtrace hard error and turns it into a human-friendly hard-error. It does not preclude any further better support and the work done here to identify VCS requirements in the 1st place is needed for any efforts of that sort. So ... this should be completely uncontroversial.

**Review by stuhood — APPROVED** [review]
Ok, thanks.

I think that I interpreted:
> Unlike local project requirements though, the failure to handle these requirements was uncontrolled.

... as meaning that we would still successfully build/install the requirement in question, but then not actually successfully lock as described in https://github.com/pantsbuild/pex/issues/1562#issuecomment-1009199447... i.e., that re-running immediately would get you what you wanted, but that re-running at some point in the future might not.

**Comment by Eric-Arellano** [comment]
Thank you, John. This looks great.

**Pull request merged**
