### PR TITLE
Support uncompressed PEXes.

### LINKED ISSUE #1686: Expose compression control for Pex zipping operations.
The experiments [here](https://github.com/pantsbuild/pex/issues/1675#issuecomment-1072451741) and [here](https://github.com/pantsbuild/pex/issues/1675#issuecomment-1075737047) in #1675 prove out that the zip compression level provides a significant swing in tradeoffs. It's probably worth exposing this to let users decide where they want to land in the tradeoff spectrum.

### PR DESCRIPTION
**Pull request by jsirois**
Closes #1686

### CODE REVIEW

**Comment by jsirois** [comment]
The motivating case from #1675:

```
$ time python3.8 -mpex -v -r lock.txt -o compressed.pex
...
pex:       Installing 135 distributions: 3053.3ms
pex:       Checking install: 535.2ms
Saving PEX file to compressed.pex
pex: Zipping PEX file.: 125816.6ms

real	2m44.588s
user	2m23.503s
sys	0m6.389s

$ time python3.8 -mpex -v -r lock.txt -o un-compressed.pex --no-compress
pex:       Installing 135 distributions: 2970.2ms
pex:       Checking install: 531.3ms
Saving PEX file to un-compressed.pex
pex: Zipping PEX file.: 5055.3ms

real	0m43.521s
user	0m22.528s
sys	0m6.339s

$ ls -lh compressed.pex un-compressed.pex 
-rwxr-xr-x 1 jsirois jsirois 1.8G Apr  4 13:04 compressed.pex
-rwxr-xr-x 1 jsirois jsirois 3.8G Apr  4 13:05 un-compressed.pex

$ time python3.8 -mpex -v --pex-repository compressed.pex -r subset.txt -o compressed.subset.pex
pex: Building pex: 763.9ms                                                                                                                                                                                                                                      
pex:   Resolving distributions (subset.txt): 763.7ms
pex:     Resolving requirements from PEX compressed.pex.: 761.8ms
pex:       Laying out PEX zipfile compressed.pex: 119.5ms
pex:         Installing compressed.pex to /home/jsirois/.pex/unzipped_pexes/8b433f67c641a262e86ed13ea8db9e27743c9094: 119.3ms
Saving PEX file to compressed.subset.pex
pex: Zipping PEX file.: 120682.5ms

real	2m1.633s
user	1m59.387s
sys	0m2.131s

$ time python3.8 -mpex -v --pex-repository un-compressed.pex -r subset.txt -o un-compressed.subset.pex --no-compress
pex: Building pex: 666.1ms                                                                                                                                 
pex:   Resolving distributions (subset.txt): 665.9ms
pex:     Resolving requirements from PEX un-compressed.pex.: 663.8ms
pex:       Laying out PEX zipfile un-compressed.pex: 0.1ms
Saving PEX file to un-compressed.subset.pex
Previous binary unexpectedly exists, cleaning: un-compressed.subset.pex~
pex: Zipping PEX file.: 5242.6ms

real	0m6.096s
user	0m2.921s
sys	0m2.517s

$ ls -lh compressed.subset.pex un-compressed.subset.pex 
-rwxr-xr-x 1 jsirois jsirois 1.8G Apr  4 13:09 compressed.subset.pex
-rwxr-xr-x 1 jsirois jsirois 3.7G Apr  4 13:10 un-compressed.subset.pex
```

**Review by Eric-Arellano — APPROVED** [review]
If Pants didn't exist, would you still want to land this? I don't think Pants is very likely to use this now that we have Pex lock files and direct subsetting working, w/o need for repository pex

**Comment by jsirois** [comment]
> If Pants didn't exist, would you still want to land this?

Yes. And, so you know, my considerations always are for Pex as a standalone tool. It pre-dates Pants. If I add a feature for Pants only, or even have to consider Pants much, I generally consider that a bad sign.

**Comment by stuhood** [comment]
> If Pants didn't exist, would you still want to land this? I don't think Pants is very likely to use this now that we have Pex lock files and direct subsetting working, w/o need for repository pex

We'll still want to use the `packed` layout when building subsets from a lockfile... although whether skipping compression will make sense for our usecase will require benchmarking.

**Pull request merged**
