### PR TITLE
More fixes for windows

### PR DESCRIPTION
**Pull request by mikekap**
Now all the tests pass.

One thing I'm not sure about is in the first commit - perhaps we should do away with Link.local_path & make Link.path do the proper thing? I don't think there's a single user of Link.path that uses it for real urls. Let me know what you think.

### CODE REVIEW

**Comment by mikekap** [comment]
Ping :)

**Comment by mikekap** [comment]
Ping.

**Comment by mikekap** [comment]
Would this be easier to review if I made separate PRs for each commit? That would be fairly easy to do since they're not really dependent on each other.

**Comment by mikekap** [comment]
Fixed the comments; PTAL @ the link commit, since it involved some urllib.unquote additions (which I think make Link.py even more correct).

Almost feels like link.py should be open-sourced on it's own :P

**Comment by kwlzn** [comment]
lgtm! :+1:

**Comment by kwlzn** [comment]
thanks for the PR @mikekap - I'll get a release out soon so folks can consume this via pypi.

**Pull request merged**
