### PR TITLE
Make --platform/--interpreter multi-options

### PR DESCRIPTION
**Pull request by jjjake**

### CODE REVIEW

**Comment by kwlzn** [comment]
looks like this PR failed CI, so no one took a look - but it'd be great to have this feature in master.

any thoughts on getting this finalized? if time doesn't permit, you could also offer this up to another contributor to run with as it seems to be mostly there.

**Comment by jjjake** [comment]
Thanks for following up @kwlzn, 'preciate it.

I do not have the time to work on this at the moment, and would be happy to hand it off to another contributor.

FWIW, I am currently using my resolve_multi branch to generate multi-platform pex files, so hopefully there won't be too much more work. I'm not very familiar with the pex source code, though, so I may be underestimating some of the corner cases.

**Comment by mzdaniel** [comment]
Hey @jjjake . Thank you for your implementing in this feature. So far, we have now all test passing. Not sure though how the CLI should work. As per @kwkn request, I am following this discussion at #68

**Comment by kwlzn** [comment]
this has been superseded by #394 which is now in master, so closing this out. thanks @jjjake for getting the ball rolling.

**Pull request closed without merging**
