### PR TITLE
Introduce the `PEX` env var.

### LINKED ISSUE #1485: How to know whether we are running from within pex
Hello there!
I recently bumped the pex version of our project and figured out that the hack (import _pex) that we were using to detect whether or not we are running from within a pex does not work anymore. Here is the initial discussion about it started in 2019 by one of my colleagues: https://github.com/pantsbuild/pex/issues/721
Is there a new way to detect that we are in a pex ?
Thanks in advance.

### PR DESCRIPTION
**Pull request by jsirois**
This is now always exposed to Pex applications so they can uniformly
detect that they are running from a PEX vs. from a virtual environment
or similar.

Closes #1485

### CODE REVIEW

**Comment by jsirois** [comment]
Hopefully this does the trick @nateagr.

**Comment by jsirois** [comment]
The CI break is un-related. Fixing in #1496 and will re-base.

**Review by Eric-Arellano — APPROVED** [review]
Thanks!

**Comment by nateagr** [comment]
> Hopefully this does the trick @nateagr.

Perfect! Thanks a lot @jsirois

**Pull request merged**
