### PR TITLE
Support PEP-503 name normalization.

### LINKED ISSUE #614: Pex cannot correctly resolve between multiple transitive dependencies
Reproduction:
`pex apache-airflow==1.10.0 --interpreter-constraint='CPython<3.7'`
Pex version:
pex 1.5.1

Problem: 
Above command gives output of 
```
Could not satisfy all requirements for flask-login==0.2.11:
    flask-login==0.2.11(from: apache-airflow==1.10.0), Flask-Login<0.5,>=0.3(from: apache-airflow==1.10.0->flask-appbuilder<2.0.0,>=1.11.1)
```

Airflow 1.10.0's setup.py denotes flask-login of 0.2.11. https://github.com/apache/incubator-airflow/blob/1.10.0/setup.py#L280

However, it also depends on flask-appbuilder with a constraint of `<2.0.0,>=1.11.1`.
Looking at two different versions of flask-appbuilder:
https://github.com/dpgaspar/Flask-AppBuilder/blob/v1.11.1/setup.py#L41 vs https://github.com/dpgaspar/Flask-AppBuilder/blob/v1.12.1/setup.py#L42

1.11.1 and 1.12.1 both meet the requirement of `<2.0.0,>=1.11.1` but they require incompatible versions of `flask-login`. Pex should be able to resolve to the earlier version and pick up `flask-login` 0.2.11.

### LINKED ISSUE #641: Dependency resolution can't handle PEP 503-style normalized package names
PyPI and setuptools support package name normalization as per PEP 503: https://www.python.org/dev/peps/pep-0503/#normalized-names

This means that a package like https://pypi.org/project/pytest-selenium/ can be installed both with `pip install pytest.selenium` and `pip install pytest-selenium`.

pex only accepts already normalized package names. If I put `pytest.selenium` in a `requirements.txt` file this won't work:

```
$ pex -o pex.bin -vvvv -r requirements.txt 
pex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x107466910>
pex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x10701c950>
pex: crawling link i=0 link=Link('file:///Users/nik/.pex/build') follow_links=False
pex: crawling link i=0 link=Link('https://pypi.org/simple/pytest-selenium/') follow_links=False
Could not satisfy all requirements for pytest.selenium:
    pytest.selenium
```

Same works with `pytest-selenium`.

For consistency with other build tools pex should support this as well. Arguably the PEP 503 behavior is weird (I only just learned about it today too) and probably bad design. But consistency across tools might trump bad design decisions. I came across this because a user was trying an existing requirements file that had always worked for them with pip and couldn't figure out why it failed in pex.

### PR DESCRIPTION
**Pull request by jsirois**
Fixes #641

### CODE REVIEW

**Comment by jsirois** [comment]
Not for review yet - this needs a test.

**Comment by JustinVenus** [comment]
Thanks a lot for working on this @jsirois ... I'm having a lot of success w/ this patch so far.  I've monkey patched pants-1.70/pex-1.3.2 like so https://gist.github.com/JustinVenus/2fece24acfb376553a629c805ae6eace

**Comment by jsirois** [comment]
I'm not sure how I lost track of this one, but I've re-based. I'm going to sit on it though and prefer the work in #781 to fix this bug if that work is accepted.

**Comment by jsirois** [comment]
Since #781 is now merged I'm going to drop this.

**Pull request closed without merging**
