### PR TITLE
Prepare the `1.1.5` release.

### PR DESCRIPTION
**Pull request by jsirois**

### CODE REVIEW

**Comment by jsirois** [comment]
@kwlzn - If you have a chance to take a look I'd be grateful.
The changelog is rendered here: https://github.com/jsirois/pex/blob/jsirois/1.1.5/prepare_release/CHANGES.rst

**Comment by jsirois** [comment]
This addresses #237

**Comment by kwlzn** [comment]
@jsirois lgtm!

**Comment by jsirois** [comment]
Thanks @kris - patched in master @ https://github.com/pantsbuild/pex/commit/2cb2233820038596c424fbce548e7a4393035afe

**Pull request closed without merging**
